name: Delphi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        sudo apt-get install -y libsecp256k1-dev
        python -m pip install --upgrade pip setuptools==51.1.0 wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Start flextesa sandbox
      run: docker run --rm -p 8732:20000 --detach tqtezos/flextesa:20201214 delphibox start
    - name: Sleep for 20 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '20s' 
    - name: Run tests
      run: pytest test -v
